#!/usr/bin/env bash

# default
sudo dnf5 install git neovim tmux keepassxc stow thunderbird \
	btop gimp calibre fzf ripgrep keychain obs-studio uxplay dunst
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

