#!/usr/bin/env bash

# default
sudo dnf5 install git neovim polybar rofi tmux keepassxc stow flameshot thunderbird btop gimp \
    calibre fzf ripgrep keychain obs-studio
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

