#!/usr/bin/env bash

# dependencies
sudo dnf install gtk4-devel gtk4-layer-shell-devel libadwaita-devel blueprint-compiler gettext

# get correct zig
curl https://www.zvm.app/install.sh | bash
zvm i 0.15.2

# get ghostty
git clone git@github.com:ghostty-org/ghostty.git $HOME/src/ghostty
cd $HOME/src/ghostty
zig build -p $HOME/.local -Doptimize=ReleaseFast

